[package]
name = "hash_finder"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = { version = "0.10.8", features = ["asm", "asm-aarch64"] }

num_cpus = "1.16.0"
clap = { version = "4.5.23", features = ["derive"] }
rayon = "1.10.0"
